version: "3.7"
services:
  database:
    container_name: ${PROJECT_NAME}_database
    image: mariadb:10
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_PASSWORD: "true"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb:/var/lib/mysql

  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: ./docker/php
    ports:
      - ${WEB_CONTAINER_PORT}:80
    volumes:
      - ./backend/:/var/www/${PROJECT_NAME}
      - ./docker/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - database

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./backend/:/var/www/${PROJECT_NAME}
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  phpmyadmin:
    container_name: ${PROJECT_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - database

  frontend:
    container_name: ${PROJECT_NAME}_frontend
    build:
      context: ./docker/node
    ports:
      - "8082:8082"
    volumes:
      - ./frontend/:/app
      - exclude:/app/node_modules/
    depends_on:
      - nginx
volumes:
    exclude: